version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - JWT_SECRET=secure_jwt_secret_must_be_32_characters_long
      - JWT_EXPIRES_IN=1d
      - MONGO_URI=mongodb://mongodb:27107/ecommerce
      - ALLOWED_ORIGINS=*
      - SEED_ADMIN_PHONE=9999999999
      - SEED_ADMIN_PIN=9999
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
